### ISSUE TITLE
本の高さを実装するかどうか

### ISSUE THREAD

**Issue by HakuryuSato** [HakuryuSato/APPRENTICE-TEAMDEV-1-TEAM4#27]
実装する場合追加作業が必要なため、採決をとりたい。
一旦未実装の場合はクローズとする

https://github.com/HakuryuSato/APPRENTICE-TEAMDEV-1-TEAM4/pull/26#pullrequestreview-2274239222

**Comment by hiderits8** [comment]
高さ実装なしは大丈夫。
ただ、現状本の種類が6色しかないので、追加で色やパターンが欲しいのであれば早めに欲しい。
もしくは、現在1番高い112pxの本に合わせて画像自体の高さをすべて112pxにして、低い本は上側を透過させた画像に差し替えるも可能。

**Comment by HakuryuSato** [comment]
実装する
