### ISSUE TITLE
偉人モーダル部分のフォントについて

### ISSUE THREAD

**Issue by hiderits8** [HakuryuSato/APPRENTICE-TEAMDEV-1-TEAM4#50]
デフォルトの書体がちょっとポップめなものなので、偉人部分のフォントを若干滲んだレトロなものにしたいです。
実装は15分くらいあればできます。

しっぽり明朝B1-Regular
https://fonts.google.com/specimen/Shippori+Mincho+B1?subset=japanese

**Comment by HakuryuSato** [comment]
是非お願いします！
